development:
  adapter: postgresql
  encoding: unicode
  database: post_development
  pool: 5
  port: 5432
  username: postgres
  password: Pa$$w0rd

test:
  adapter: postgresql
  encoding: unicode
  database: post_test
  pool: 5
  port: 5432
  username: postgres
  password: Pa$$w0rd